import type {
  BossGemDropPackDistributionRecord,
  BossGemDropPackMeanRecord,
  BossGemWorldLevelDropRecord,
  DomainOfForgeryRecord,
  DomainOfMasteryRecord,
  NormalBossUniqueMaterialDropRecord,
  PlannerDefaults,
  PlannerDomainLevel,
  ResinActivityCosts,
  ResinRules,
  ResinSystem,
  TalentBookDomainDropModelRecord,
  TrounceDomainRecord,
  WeeklyTalentMaterialDropRecord,
  WeaponAscensionDomainDropModelRecord,
  LeyLineRewardRecord,
} from "./types";

export const RESIN_SYSTEM: ResinSystem = {
  originalResin: {
    softCap: 200,
    hardCapAfterManualRefill: 2000,
    regenMinutesPerResin: 8,
    resinPerHour: 7.5,
    resinPerDay: 180,
    resinPerWeek: 1260,
    fullRechargeFromZeroMinutes: 1600,
    fullRechargeFromZeroHours: 26 + 40 / 60,
  },
  adventureExpRatio: {
    resinToAdventureExp: 5,
    note: "Any Original Resin spent, excluding conversion into Condensed Resin, awards Adventure EXP at a 1:5 ratio. Example: 20 Resin -> 100 Adventure EXP.",
  },
  manualRefill: {
    resinPerUse: 60,
    canExceedSoftCap: true,
    cannotRefillAbove: 1940,
    maxAfterRefill: 2000,
    fragileResinRestores: 60,
    transientResinRestores: 60,
    primogemRefillsPerDay: 6,
    primogemRefillSchedule: [
      { refillNumber: 1, primogems: 50, totalPrimogems: 50, maxTotalResin: 60, resinPerPrimogemTotal: 1.2 },
      { refillNumber: 2, primogems: 100, totalPrimogems: 150, maxTotalResin: 120, resinPerPrimogemTotal: 0.8 },
      { refillNumber: 3, primogems: 100, totalPrimogems: 250, maxTotalResin: 180, resinPerPrimogemTotal: 0.72 },
      { refillNumber: 4, primogems: 150, totalPrimogems: 400, maxTotalResin: 240, resinPerPrimogemTotal: 0.6 },
      { refillNumber: 5, primogems: 200, totalPrimogems: 600, maxTotalResin: 300, resinPerPrimogemTotal: 0.5 },
      { refillNumber: 6, primogems: 200, totalPrimogems: 800, maxTotalResin: 360, resinPerPrimogemTotal: 0.45 },
    ],
  },
};

export const RESIN_ACTIVITY_COSTS: ResinActivityCosts = {
  leyLineOutcrop: {
    resin: 20,
    condensedResinAllowed: true,
    condensedResinEquivalentResin: 40,
    adventureExpPer20ResinClaim: 100,
  },
  domain: {
    resin: 20,
    condensedResinAllowed: true,
    condensedResinEquivalentResin: 40,
    adventureExpPer20ResinClaim: 100,
  },
  normalBoss: {
    resin: 40,
    condensedResinAllowed: false,
    adventureExpPerClaim: 200,
  },
  weeklyBoss: {
    firstThreePerWeekResin: 30,
    afterFirstThreePerWeekResin: 60,
    condensedResinAllowed: false,
    adventureExpPerDiscountedClaim: 150,
    adventureExpPerFullCostClaim: 300,
    rewardLimitPerBossPerWeek: 1,
    weeklyDiscountedClaims: 3,
  },
};

export const LEY_LINE_REWARDS_BY_WORLD_LEVEL: Record<string, LeyLineRewardRecord> = {
  "0": {
    enemyLevel: "12",
    adventureExp: 100,
    companionshipExp: 10,
    revelation: {
      characterExpMaterials: {
        WanderersAdvice: { min: 7, max: 8 },
        AdventurersExperience: { min: 3, max: 4 },
      },
      averageCharacterExp: 25000,
      averageEfficiencyPercent: 20.4,
    },
    wealth: {
      mora: 12000,
      efficiencyPercent: 20.0,
    },
  },
  "1": {
    enemyLevel: "25",
    adventureExp: 100,
    companionshipExp: 15,
    revelation: {
      characterExpMaterials: {
        WanderersAdvice: { min: 10, max: 12 },
        AdventurersExperience: { min: 5, max: 6 },
      },
      averageCharacterExp: 38500,
      averageEfficiencyPercent: 31.4,
    },
    wealth: {
      mora: 20000,
      efficiencyPercent: 33.3,
    },
  },
  "2": {
    enemyLevel: "34",
    adventureExp: 100,
    companionshipExp: 15,
    revelation: {
      characterExpMaterials: {
        AdventurersExperience: { min: 10, max: 11 },
      },
      averageCharacterExp: 52500,
      averageEfficiencyPercent: 42.9,
    },
    wealth: {
      mora: 28000,
      efficiencyPercent: 46.7,
    },
  },
  "3": {
    enemyLevel: "46",
    adventureExp: 100,
    companionshipExp: 15,
    revelation: {
      characterExpMaterials: {
        AdventurersExperience: { min: 13, max: 14 },
      },
      averageCharacterExp: 67500,
      averageEfficiencyPercent: 55.1,
    },
    wealth: {
      mora: 36000,
      efficiencyPercent: 60.0,
    },
  },
  "4": {
    enemyLevel: "61",
    adventureExp: 100,
    companionshipExp: 15,
    revelation: {
      characterExpMaterials: {
        AdventurersExperience: { min: 6, max: 7 },
        HerosWit: { min: 2, max: 3 },
      },
      averageCharacterExp: 82500,
      averageEfficiencyPercent: 67.3,
    },
    wealth: {
      mora: 44000,
      efficiencyPercent: 73.3,
    },
  },
  "5": {
    enemyLevel: "71",
    adventureExp: 100,
    companionshipExp: 20,
    revelation: {
      characterExpMaterials: {
        AdventurersExperience: { min: 6, max: 7 },
        HerosWit: { min: 3, max: 4 },
      },
      averageCharacterExp: 102500,
      averageEfficiencyPercent: 83.7,
    },
    wealth: {
      mora: 52000,
      efficiencyPercent: 86.7,
    },
  },
  "6": {
    enemyLevel: "78",
    adventureExp: 100,
    companionshipExp: 20,
    revelation: {
      characterExpMaterials: {
        AdventurersExperience: { min: 6, max: 7 },
        HerosWit: { min: 4, max: 5 },
      },
      averageCharacterExp: 122500,
      averageEfficiencyPercent: null,
    },
    wealth: {
      mora: 60000,
      efficiencyPercent: null,
    },
  },
  "7": {
    enemyLevel: "84",
    adventureExp: 100,
    companionshipExp: 20,
    revelation: {
      characterExpMaterials: {
        AdventurersExperience: { min: 6, max: 7 },
        HerosWit: { min: 4, max: 5 },
      },
      averageCharacterExp: 122500,
      averageEfficiencyPercent: null,
    },
    wealth: {
      mora: 60000,
      efficiencyPercent: null,
    },
  },
  "8": {
    enemyLevel: "85-86",
    adventureExp: 100,
    companionshipExp: 20,
    revelation: {
      characterExpMaterials: {
        AdventurersExperience: { min: 6, max: 7 },
        HerosWit: { min: 4, max: 5 },
      },
      averageCharacterExp: 122500,
      averageEfficiencyPercent: null,
    },
    wealth: {
      mora: 60000,
      efficiencyPercent: null,
    },
  },
  "9": {
    enemyLevel: "95",
    adventureExp: 100,
    companionshipExp: 20,
    revelation: {
      characterExpMaterials: {
        AdventurersExperience: { min: 6, max: 7 },
        HerosWit: { min: 4, max: 5 },
      },
      averageCharacterExp: 122500,
      averageEfficiencyPercent: null,
    },
    wealth: {
      mora: 60000,
      efficiencyPercent: null,
    },
  },
};

export const DOMAINS_OF_FORGERY: Record<string, DomainOfForgeryRecord> = {
  LostMooncourt: {
    name: "Lost Mooncourt",
    region: "Nod-Krai",
    location: "Hiisi Island, Nod-Krai",
    activityType: "domain_of_forgery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [15, 21, 30, 40],
    partyLevelRecommendations: [15, 36, 59, 80],
    elements: ["Dendro", "Hydro", "Electro", "Pyro"],
    weaponAscensionFamilies: ["ArtfulDevice", "LongNightFlint", "FarNorthScions"],
    listedRewards: ["Artful Device Fragment", "Afterglow of Long Night Flint", "Oblation of the Far-North Scions"],
  },
  AncientWatchtower: {
    name: "Ancient Watchtower",
    region: "Natlan",
    location: "Coatepec Mountain, Natlan",
    activityType: "domain_of_forgery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [16, 21, 30, 40],
    partyLevelRecommendations: [15, 36, 59, 80],
    elements: ["Hydro", "Electro", "Pyro", "Cryo"],
    weaponAscensionFamilies: ["BlazingSacrificialHeart", "SacredLord", "NightWind"],
    listedRewards: ["Blazing Sacrificial Heart's Terror", "Delirious Desolation of the Sacred Lord", "Night-Wind's Mystic Augury"],
  },
  CeciliaGarden: {
    name: "Cecilia Garden",
    region: "Mondstadt",
    location: "Wolvendom, Windwail Highland, Mondstadt",
    activityType: "domain_of_forgery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [16, 21, 30, 40],
    partyLevelRecommendations: [15, 36, 59, 80],
    elements: ["Electro"],
    weaponAscensionFamilies: ["Decarabian", "BorealWolf", "DandelionGladiator"],
    listedRewards: ["Tile of Decarabian's Tower", "Boreal Wolf's Cracked Tooth", "Shackles of the Dandelion Gladiator"],
  },
  CourtOfFlowingSand: {
    name: "Court of Flowing Sand",
    region: "Inazuma",
    location: "Mt. Yougou, Narukami Island, Inazuma",
    activityType: "domain_of_forgery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [16, 21, 30, 40],
    partyLevelRecommendations: [15, 36, 59, 80],
    elements: ["Geo", "Cryo"],
    weaponAscensionFamilies: ["DistantSea", "Narukami", "Mask"],
    listedRewards: ["Coral Branch of a Distant Sea", "Narukami's Joy", "Mask of the One-Horned"],
  },
  EchoesOfTheDeepTides: {
    name: "Echoes of the Deep Tides",
    region: "Fontaine",
    location: "Court of Fontaine Region, Fontaine",
    activityType: "domain_of_forgery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [16, 21, 30, 40],
    partyLevelRecommendations: [15, 36, 59, 80],
    elements: ["Hydro", "Pyro", "Cryo", "Anemo"],
    weaponAscensionFamilies: ["AncientChord", "PureSacredDewdrop", "PristineSea"],
    listedRewards: ["Fragment of an Ancient Chord", "Sublimation of Pure Sacred Dewdrop", "Silver Goblet of the Pristine Sea"],
  },
  HiddenPalaceOfLianshanFormula: {
    name: "Hidden Palace of Lianshan Formula",
    region: "Liyue",
    location: "Mingyun Village, Qiongji Estuary, Liyue",
    activityType: "domain_of_forgery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [16, 21, 30, 40],
    partyLevelRecommendations: [15, 36, 59, 80],
    elements: ["Cryo"],
    weaponAscensionFamilies: ["Guyun", "MistVeiledElixir", "Aerosiderite"],
    listedRewards: ["Luminous Sands from Guyun", "Mist Veiled Mercury Elixir", "Bit of Aerosiderite"],
  },
  TowerOfAbjectPride: {
    name: "Tower of Abject Pride",
    region: "Sumeru",
    location: "Apam Woods, Ashavan Realm, Sumeru",
    activityType: "domain_of_forgery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [16, 21, 30, 40],
    partyLevelRecommendations: [15, 36, 59, 80],
    elements: ["Dendro", "Electro"],
    weaponAscensionFamilies: ["ForestDew", "OasisGarden", "ScorchingMight"],
    listedRewards: ["Copper Talisman of the Forest Dew", "Oasis Garden's Kindness", "Dream of Scorching Might"],
  },
};

export const DOMAINS_OF_MASTERY: Record<string, DomainOfMasteryRecord> = {
  LightlessCapital: {
    name: "Lightless Capital",
    region: "Nod-Krai",
    location: "Lempo Isle, Nod-Krai",
    activityType: "domain_of_mastery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [],
    partyLevelRecommendations: [38, 54, 71, 88],
    elements: ["Hydro", "Electro"],
    talentFamilies: ["Moonlight", "Elysium", "Vagrancy"],
    listedRewards: ["Teachings of Moonlight", "Guide to Elysium", "Philosophies of Vagrancy"],
  },
  BlazingRuins: {
    name: "Blazing Ruins",
    region: "Natlan",
    location: "Coatepec Mountain, Natlan",
    activityType: "domain_of_mastery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [27, 28, 36, 45],
    partyLevelRecommendations: [38, 54, 71, 88],
    elements: ["Dendro", "Electro", "Anemo", "Hydro"],
    talentFamilies: ["Contention", "Kindling", "Conflict"],
    listedRewards: ["Teachings of Contention", "Guide to Kindling", "Philosophies of Conflict"],
  },
  ForsakenRift: {
    name: "Forsaken Rift",
    region: "Mondstadt",
    location: "Springvale, Windwail Highland, Mondstadt",
    activityType: "domain_of_mastery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [27, 28, 36, 45],
    partyLevelRecommendations: [38, 54, 71, 88],
    elements: ["Pyro"],
    talentFamilies: ["Freedom", "Resistance", "Ballad"],
    listedRewards: ["Teachings of Freedom", "Guide to Resistance", "Philosophies of Ballad"],
  },
  PaleForgottenGlory: {
    name: "Pale Forgotten Glory",
    region: "Fontaine",
    location: "Salacia Plain, Court of Fontaine Region, Fontaine",
    activityType: "domain_of_mastery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [27, 28, 36, 45],
    partyLevelRecommendations: [38, 54, 71, 88],
    elements: ["Geo", "Hydro", "Pyro", "Cryo", "Electro"],
    talentFamilies: ["Equity", "Justice", "Order"],
    listedRewards: ["Teachings of Equity", "Guide to Justice", "Philosophies of Order"],
  },
  SteepleOfIgnorance: {
    name: "Steeple of Ignorance",
    region: "Sumeru",
    location: "Chatrakam Cave, Lokapala Jungle, Sumeru",
    activityType: "domain_of_mastery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [27, 28, 36, 45],
    partyLevelRecommendations: [38, 54, 71, 88],
    elements: ["Dendro", "Electro", "Pyro", "Hydro"],
    talentFamilies: ["Admonition", "Ingenuity", "Praxis"],
    listedRewards: ["Teachings of Admonition", "Guide to Ingenuity", "Philosophies of Praxis"],
  },
  TaishanMansion: {
    name: "Taishan Mansion",
    region: "Liyue",
    location: "Jueyun Karst, Minlin, Liyue",
    activityType: "domain_of_mastery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [27, 28, 36, 45],
    partyLevelRecommendations: [38, 54, 71, 88],
    elements: ["Hydro", "Cryo", "Electro"],
    talentFamilies: ["Prosperity", "Diligence", "Gold"],
    listedRewards: ["Teachings of Prosperity", "Guide to Diligence", "Philosophies of Gold"],
  },
  VioletCourt: {
    name: "Violet Court",
    region: "Inazuma",
    location: "Kannazuka, Inazuma",
    activityType: "domain_of_mastery",
    resinCost: 20,
    condensedResinAllowed: true,
    adventureRankRequirements: [27, 28, 36, 45],
    partyLevelRecommendations: [38, 54, 71, 88],
    elements: ["Electro"],
    talentFamilies: ["Transience", "Elegance", "Light"],
    listedRewards: ["Teachings of Transience", "Guide to Elegance", "Philosophies of Light"],
  },
};

export const TROUNCE_DOMAINS: Record<string, TrounceDomainRecord> = {
  ConfrontStormterror: {
    name: "Confront Stormterror",
    region: "Mondstadt",
    location: "Stormterror's Lair, Brightcrown Mountains, Mondstadt",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [25, 30, 35, 40, 45, 50],
    partyLevelRecommendations: [40, 50, 60, 70, 80, 90],
    weeklyTalentMaterials: ["Dvalin's Plume", "Dvalin's Claw", "Dvalin's Sigh"],
  },
  BeneathTheDragonQueller: {
    name: "Beneath the Dragon-Queller",
    region: "Liyue",
    location: "Nantianmen, Minlin, Liyue",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [35, 40, 45, 50],
    partyLevelRecommendations: [60, 70, 80, 90],
    weeklyTalentMaterials: ["Dragon Lord's Crown", "Bloodjade Branch", "Gilded Scale"],
  },
  EndOfTheOneiricEuthymia: {
    name: "End of the Oneiric Euthymia",
    region: "Inazuma",
    location: "Mt. Yougou, Narukami Island, Inazuma",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [35, 40, 45, 50],
    partyLevelRecommendations: [60, 70, 80, 90],
    weeklyTalentMaterials: ["Mudra of the Malefic General", "Tears of the Calamitous God", "The Meaning of Aeons"],
  },
  EnterTheGoldenHouse: {
    name: "Enter the Golden House",
    region: "Liyue",
    location: "Mt. Tianheng, Sea of Clouds, Liyue",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [35, 40, 45, 50],
    partyLevelRecommendations: [60, 70, 80, 90],
    weeklyTalentMaterials: ["Tusk of Monoceros Caeli", "Shard of a Foul Legacy", "Shadow of the Warrior"],
  },
  FalseMoonInstitute: {
    name: "False Moon Institute",
    region: "Nod-Krai",
    location: "Special Territory Research Institute, Ashveil Peak, Nod-Krai",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [35, 40, 45, 50],
    partyLevelRecommendations: [60, 70, 80, 90],
    weeklyTalentMaterials: ["Mask of the Virtuous Doctor", "Madman's Restraint", "Elixir of the Heretic"],
  },
  JoururiWorkshop: {
    name: "Joururi Workshop",
    region: "Sumeru",
    location: "Chinvat Ravine, Avidya Forest, Sumeru",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [35, 40, 45, 50],
    partyLevelRecommendations: [60, 70, 80, 90],
    weeklyTalentMaterials: ["Puppet Strings", "Mirror of Mushin", "Daka's Bell"],
  },
  NarukamiIslandTenshukaku: {
    name: "Narukami Island: Tenshukaku",
    region: "Inazuma",
    location: "Inazuma City, Narukami Island, Inazuma",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [35, 40, 45, 50],
    partyLevelRecommendations: [60, 70, 80, 90],
    weeklyTalentMaterials: ["Molten Moment", "Hellfire Butterfly", "Ashen Heart"],
  },
  ShadowOfAnotherWorld: {
    name: "Shadow of Another World",
    region: "Fontaine",
    location: "Salacia Plain, Court of Fontaine Region, Fontaine",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [35, 40, 45, 50],
    partyLevelRecommendations: [60, 70, 80, 90],
    weeklyTalentMaterials: ["Lightless Silk String", "Lightless Eye of the Maelstrom", "Lightless Mass"],
  },
  StoneSteleRecords: {
    name: "Stone Stele Records",
    region: "Natlan",
    location: "Tezcatepetonco Range, Natlan",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [35, 40, 45, 50],
    partyLevelRecommendations: [60, 70, 80, 90],
    weeklyTalentMaterials: ["Eroded Horn", "Eroded Sunfire", "Eroded Scale-Feather"],
  },
  TheRealmOfBeginnings: {
    name: "The Realm of Beginnings",
    region: "Sumeru",
    location: "Apep's Resort, Desert of Hadramaveth, Sumeru",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [35, 40, 45, 50],
    partyLevelRecommendations: [60, 70, 80, 90],
    weeklyTalentMaterials: ["Worldspan Fern", "Primordial Greenbloom", "Everamber"],
  },
  UnresolvedChessGame: {
    name: "Unresolved Chess Game",
    region: "Mondstadt",
    location: "Falcon Coast, Galesong Hill, Mondstadt",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [35, 40, 45, 50],
    partyLevelRecommendations: [60, 70, 80, 90],
    weeklyTalentMaterials: ["Ascended Sample Knight", "Ascended Sample Rook", "Ascended Sample Queen"],
  },
  ScatteredRuins: {
    name: "Scattered Ruins",
    region: "Fontaine",
    location: "Mont Esus East, Liffey Region, Fontaine",
    activityType: "trounce_domain",
    resinCostFirstThreeWeekly: 30,
    resinCostAfterFirstThreeWeekly: 60,
    rewardLimit: "once_per_boss_per_week",
    adventureRankRequirements: [40, 45, 50],
    partyLevelRecommendations: [60, 70, 80, 90],
    weeklyTalentMaterials: ["Fading Candle", "Silken Feather", "Denial and Judgment"],
  },
};

export const WEAPON_ASCENSION_DOMAIN_DROP_MODEL: Record<PlannerDomainLevel, WeaponAscensionDomainDropModelRecord> = {
  I: {
    domainLevel: "I",
    resinCost: 20,
    overall: {
      twoStar: { range: "4-6", average: 4.7 },
      threeStar: null,
      fourStar: null,
      fiveStar: null,
    },
    twoStarRollMean: 2.2,
    dropPackMean: 2.5,
    dropPackDistribution: {
      twoStar: 1.0,
      threeStar: 0,
      fourStar: 0,
      fiveStar: 0,
    },
  },
  II: {
    domainLevel: "II",
    resinCost: 20,
    overall: {
      twoStar: { range: "2-3", average: 2.7 },
      threeStar: { range: "2", average: 2.0 },
      fourStar: null,
      fiveStar: null,
    },
    twoStarRollMean: 2.7,
    dropPackMean: 2.0,
    dropPackDistribution: {
      twoStar: 0,
      threeStar: 1.0,
      fourStar: 0,
      fiveStar: 0,
    },
  },
  III: {
    domainLevel: "III",
    resinCost: 20,
    overall: {
      twoStar: { range: "2-3", average: 2.26 },
      threeStar: { range: "0-3", average: 2.76 },
      fourStar: { range: "0-3", average: 0.24 },
      fiveStar: null,
    },
    twoStarRollMean: 2.26,
    dropPackMean: 3.0,
    dropPackDistribution: {
      twoStar: 0,
      threeStar: 0.92,
      fourStar: 0.08,
      fiveStar: 0,
    },
  },
  IV: {
    domainLevel: "IV",
    resinCost: 20,
    overall: {
      twoStar: { range: "2-3", average: 2.2 },
      threeStar: { range: "0-4", average: 2.418 },
      fourStar: { range: "0-4", average: 0.62 },
      fiveStar: { range: "0-4", average: 0.062 },
    },
    twoStarRollMean: 2.2,
    dropPackMean: 3.1,
    dropPackDistribution: {
      twoStar: 0,
      threeStar: 0.78,
      fourStar: 0.20,
      fiveStar: 0.02,
    },
  },
};

export const TALENT_BOOK_DOMAIN_DROP_MODEL: Record<PlannerDomainLevel, TalentBookDomainDropModelRecord> = {
  I: {
    domainLevel: "I",
    resinCost: 20,
    overall: {
      twoStar: { range: "3-4", average: 3.2 },
      threeStar: null,
      fourStar: null,
    },
    twoStarRollMean: 2.2,
    dropPackMean: 1.0,
    dropPackDistribution: {
      twoStar: 1.0,
      threeStar: 0,
      fourStar: 0,
    },
  },
  II: {
    domainLevel: "II",
    resinCost: 20,
    overall: {
      twoStar: { range: "2-3", average: 2.5 },
      threeStar: { range: "1", average: 1.0 },
      fourStar: null,
    },
    twoStarRollMean: 2.5,
    dropPackMean: 1.0,
    dropPackDistribution: {
      twoStar: 0,
      threeStar: 1.0,
      fourStar: 0,
    },
  },
  III: {
    domainLevel: "III",
    resinCost: 20,
    overall: {
      twoStar: { range: "1-2", average: 1.8 },
      threeStar: { range: "2", average: 2.0 },
      fourStar: null,
    },
    twoStarRollMean: 1.8,
    dropPackMean: 2.0,
    dropPackDistribution: {
      twoStar: 0,
      threeStar: 1.0,
      fourStar: 0,
    },
  },
  IV: {
    domainLevel: "IV",
    resinCost: 20,
    overall: {
      twoStar: { range: "2-3", average: 2.2 },
      threeStar: { range: "0-3", average: 1.98 },
      fourStar: { range: "0-3", average: 0.22 },
    },
    twoStarRollMean: 2.2,
    dropPackMean: 2.2,
    dropPackDistribution: {
      twoStar: 0,
      threeStar: 0.90,
      fourStar: 0.10,
    },
  },
};

export const NORMAL_BOSS_ASCENSION_GEM_DROPS_BY_WORLD_LEVEL: Record<string, BossGemWorldLevelDropRecord> = {
  "0": { enemyLevel: 36, twoStar: { range: "2-3", average: 2.1057 }, threeStar: null, fourStar: null, fiveStar: null },
  "1": { enemyLevel: 37, twoStar: { range: "2-3", average: 2.1057 }, threeStar: null, fourStar: null, fiveStar: null },
  "2": { enemyLevel: 41, twoStar: { range: "0-2", average: 1.0323 }, threeStar: { range: "1-4", average: 1.2954 }, fourStar: null, fiveStar: null },
  "3": { enemyLevel: 50, twoStar: { range: "0-2", average: 1.2579 }, threeStar: { range: "1-4", average: 1.3554 }, fourStar: null, fiveStar: null },
  "4": { enemyLevel: 62, twoStar: { range: "0-2", average: 1.4835 }, threeStar: { range: "1-4", average: 1.4157 }, fourStar: { range: "0-2", average: 0.099 }, fiveStar: null },
  "5": { enemyLevel: 72, twoStar: { range: "0-3", average: 1.7091 }, threeStar: { range: "1-5", average: 1.4757 }, fourStar: { range: "0-3", average: 0.114 }, fiveStar: null },
  "6": { enemyLevel: 83, twoStar: { range: "0-3", average: 1.9354 }, threeStar: { range: "1-5", average: 1.5358 }, fourStar: { range: "0-3", average: 0.1287 }, fiveStar: { range: "0-3", average: 0.0129 } },
  "7": { enemyLevel: 91, twoStar: { range: "0-3", average: 2.1607 }, threeStar: { range: "1-5", average: 1.5961 }, fourStar: { range: "0-3", average: 0.144 }, fiveStar: { range: "0-3", average: 0.0141 } },
  "8": { enemyLevel: 93, twoStar: { range: "0-3", average: 2.1607 }, threeStar: { range: "1-5", average: 1.5961 }, fourStar: { range: "0-3", average: 0.144 }, fiveStar: { range: "0-3", average: 0.0141 } },
};

export const WEEKLY_BOSS_ASCENSION_GEM_DROPS_BY_WORLD_LEVEL: Record<string, BossGemWorldLevelDropRecord> = {
  "1": { enemyLevel: 37, twoStar: { range: "3-4", average: 3.1584 }, threeStar: null, fourStar: null, fiveStar: null },
  "2": { enemyLevel: 41, twoStar: { range: "0-3", average: 2.1416 }, threeStar: { range: "1-5", average: 1.5913 }, fourStar: null, fiveStar: null },
  "3": { enemyLevel: 50, twoStar: { range: "0-4", average: 2.4803 }, threeStar: { range: "1-6", average: 1.6813 }, fourStar: null, fiveStar: null },
  "4": { enemyLevel: 62, twoStar: { range: "0-4", average: 2.8181 }, threeStar: { range: "1-6", average: 1.7717 }, fourStar: { range: "0-4", average: 0.1881 }, fiveStar: null },
  "5": { enemyLevel: 72, twoStar: { range: "0-5", average: 3.157 }, threeStar: { range: "1-7", average: 1.8617 }, fourStar: { range: "0-5", average: 0.2106 }, fiveStar: null },
  "6": { enemyLevel: 83, twoStar: { range: "0-5", average: 3.4963 }, threeStar: { range: "1-7", average: 1.9518 }, fourStar: { range: "0-5", average: 0.2325 }, fiveStar: { range: "0-5", average: 0.0233 } },
  "7": { enemyLevel: 91, twoStar: { range: "0-6", average: 3.8343 }, threeStar: { range: "1-8", average: 2.0423 }, fourStar: { range: "0-6", average: 0.2556 }, fiveStar: { range: "0-6", average: 0.025 } },
  "8": { enemyLevel: 93, twoStar: { range: "0-6", average: 3.8343 }, threeStar: { range: "1-8", average: 2.0423 }, fourStar: { range: "0-6", average: 0.2556 }, fiveStar: { range: "0-6", average: 0.025 } },
};

export const NORMAL_BOSS_UNIQUE_MATERIAL_DROP_MEAN_BY_WORLD_LEVEL: Record<string, NormalBossUniqueMaterialDropRecord> = {
  "0": { bossLevel: "36", rewardTier: 7, dropMean: 1.6185 },
  "1": { bossLevel: "37/39", rewardTier: 7, dropMean: 1.6185 },
  "2": { bossLevel: "41/42", rewardTier: 8, dropMean: 1.7037 },
  "3": { bossLevel: "50/51", rewardTier: 10, dropMean: 1.8741 },
  "4": { bossLevel: "62/63", rewardTier: 12, dropMean: 2.0445 },
  "5": { bossLevel: "72/73", rewardTier: 14, dropMean: 2.2149 },
  "6": { bossLevel: "83/84", rewardTier: 16, dropMean: 2.3852 },
  "7": { bossLevel: "91/92", rewardTier: 18, dropMean: 2.5556 },
  "8": { bossLevel: "93/94", rewardTier: 18, dropMean: 2.5556 },
};

export const WEEKLY_TALENT_MATERIAL_DROP_MEAN_BY_WORLD_LEVEL: Record<string, WeeklyTalentMaterialDropRecord> = {
  "5": { enemyLevel: 73, dropMean: 1.0 },
  "6": { enemyLevel: 84, dropMean: 1.55 },
  "7": { enemyLevel: 92, dropMean: 2.1 },
  "8": { enemyLevel: 94, dropMean: 2.4 },
};

export const BOSS_GEM_THREE_STAR_ROLL_MEAN = {
  normalBoss: 1.02,
  weeklyBoss: 1.02,
  appliesFromRewardLevel: 8,
} as const;

export const BOSS_GEM_DROP_PACK_MEAN_BY_REWARD_LEVEL: BossGemDropPackMeanRecord[] = [
  { enemyLevel: "1-4", rewardLevel: 0, normalBoss: 1.3386, weeklyBoss: 2.0079 },
  { enemyLevel: "5-9", rewardLevel: 1, normalBoss: 1.4289, weeklyBoss: 2.1432 },
  { enemyLevel: "10-14", rewardLevel: 2, normalBoss: 1.5417, weeklyBoss: 2.3124 },
  { enemyLevel: "15-19", rewardLevel: 3, normalBoss: 1.6545, weeklyBoss: 2.4816 },
  { enemyLevel: "20-24", rewardLevel: 4, normalBoss: 1.7673, weeklyBoss: 2.6508 },
  { enemyLevel: "25-29", rewardLevel: 5, normalBoss: 1.8801, weeklyBoss: 2.82 },
  { enemyLevel: "30-34", rewardLevel: 6, normalBoss: 1.9929, weeklyBoss: 2.9892 },
  { enemyLevel: "35-39", rewardLevel: 7, normalBoss: 2.1057, weeklyBoss: 3.1584 },
  { enemyLevel: "40-44", rewardLevel: 8, normalBoss: 1.3077, weeklyBoss: 2.7129 },
  { enemyLevel: "45-49", rewardLevel: 9, normalBoss: 1.4505, weeklyBoss: 2.9271 },
  { enemyLevel: "50-54", rewardLevel: 10, normalBoss: 1.5933, weeklyBoss: 3.1416 },
  { enemyLevel: "55-59", rewardLevel: 11, normalBoss: 1.7364, weeklyBoss: 3.3558 },
  { enemyLevel: "60-64", rewardLevel: 12, normalBoss: 1.9782, weeklyBoss: 3.7578 },
  { enemyLevel: "65-69", rewardLevel: 13, normalBoss: 2.1285, weeklyBoss: 3.9837 },
  { enemyLevel: "70-74", rewardLevel: 14, normalBoss: 2.2788, weeklyBoss: 4.2093 },
  { enemyLevel: "75-79", rewardLevel: 15, normalBoss: 2.4414, weeklyBoss: 4.4571 },
  { enemyLevel: "80-84", rewardLevel: 16, normalBoss: 2.5929, weeklyBoss: 4.6839 },
  { enemyLevel: "85-89", rewardLevel: 17, normalBoss: 2.7441, weeklyBoss: 4.9101 },
  { enemyLevel: "90-92", rewardLevel: 18, normalBoss: 2.895, weeklyBoss: 5.1372 },
  { enemyLevel: "93-99", rewardLevel: 19, normalBoss: 2.895, weeklyBoss: 5.1372 },
  { enemyLevel: "100-104", rewardLevel: 20, normalBoss: 2.895, weeklyBoss: 5.1372 },
];

export const BOSS_GEM_DROP_PACK_RARITY_DISTRIBUTION: BossGemDropPackDistributionRecord[] = [
  { enemyLevel: "1-4", rewardLevel: 0, twoStar: 1, threeStar: 0, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "5-9", rewardLevel: 1, twoStar: 1, threeStar: 0, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "10-14", rewardLevel: 2, twoStar: 1, threeStar: 0, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "15-19", rewardLevel: 3, twoStar: 1, threeStar: 0, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "20-24", rewardLevel: 4, twoStar: 1, threeStar: 0, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "25-29", rewardLevel: 5, twoStar: 1, threeStar: 0, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "30-34", rewardLevel: 6, twoStar: 1, threeStar: 0, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "35-39", rewardLevel: 7, twoStar: 1, threeStar: 0, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "40-44", rewardLevel: 8, twoStar: 0.789, threeStar: 0.211, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "45-49", rewardLevel: 9, twoStar: 0.789, threeStar: 0.211, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "50-54", rewardLevel: 10, twoStar: 0.789, threeStar: 0.211, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "55-59", rewardLevel: 11, twoStar: 0.789, threeStar: 0.211, fourStar: 0, fiveStar: 0 },
  { enemyLevel: "60-64", rewardLevel: 12, twoStar: 0.75, threeStar: 0.2, fourStar: 0.05, fiveStar: 0 },
  { enemyLevel: "65-69", rewardLevel: 13, twoStar: 0.75, threeStar: 0.2, fourStar: 0.05, fiveStar: 0 },
  { enemyLevel: "70-74", rewardLevel: 14, twoStar: 0.75, threeStar: 0.2, fourStar: 0.05, fiveStar: 0 },
  { enemyLevel: "75-79", rewardLevel: 15, twoStar: 0.746, threeStar: 0.199, fourStar: 0.05, fiveStar: 0.005 },
  { enemyLevel: "80-84", rewardLevel: 16, twoStar: 0.746, threeStar: 0.199, fourStar: 0.05, fiveStar: 0.005 },
  { enemyLevel: "85-89", rewardLevel: 17, twoStar: 0.746, threeStar: 0.199, fourStar: 0.05, fiveStar: 0.005 },
  { enemyLevel: "90-92", rewardLevel: 18, twoStar: 0.746, threeStar: 0.199, fourStar: 0.05, fiveStar: 0.005 },
  { enemyLevel: "93-99", rewardLevel: 19, twoStar: 0.746, threeStar: 0.199, fourStar: 0.05, fiveStar: 0.005 },
  { enemyLevel: "100-104", rewardLevel: 20, twoStar: 0.746, threeStar: 0.199, fourStar: 0.05, fiveStar: 0.005 },
];

export const PLANNER_DEFAULTS: PlannerDefaults = {
  worldLevel: 8,
  domainLevel: "IV",
  useHighestUnlockedDomain: true,
  craftAwareEstimates: true,
  naturalResinPerDay: 180,
  naturalResinPerWeek: 1260,
  assumeCondensedResinEquivalentForDomains: true,
  weeklyBossDiscountedClaimsAvailable: 3,
  includeAdventureExpEstimate: true,
  estimateOpenWorldEnemyDrops: false,
};

export const WEAPON_ASCENSION_FAMILY_TO_DOMAIN_KEY = Object.fromEntries(
  Object.entries(DOMAINS_OF_FORGERY).flatMap(([domainKey, domain]) =>
    domain.weaponAscensionFamilies.map((familyKey) => [familyKey, domainKey]),
  ),
) as Record<string, string>;

export const TALENT_FAMILY_TO_DOMAIN_KEY = Object.fromEntries(
  Object.entries(DOMAINS_OF_MASTERY).flatMap(([domainKey, domain]) => domain.talentFamilies.map((familyKey) => [familyKey, domainKey])),
) as Record<string, string>;

export const WEEKLY_TALENT_MATERIAL_TO_TROUNCE_DOMAIN_KEY = Object.fromEntries(
  Object.entries(TROUNCE_DOMAINS).flatMap(([domainKey, domain]) =>
    domain.weeklyTalentMaterials.map((materialName) => [materialName, domainKey]),
  ),
) as Record<string, string>;

export function buildPlannerResinRules(): ResinRules {
  return {
    version: 2,
    originalResinCap: RESIN_SYSTEM.originalResin.softCap,
    regenMinutesPerResin: RESIN_SYSTEM.originalResin.regenMinutesPerResin,
    naturalResinPerDay: RESIN_SYSTEM.originalResin.resinPerDay,
    naturalResinPerWeek: RESIN_SYSTEM.originalResin.resinPerWeek,
    costs: {
      domain: RESIN_ACTIVITY_COSTS.domain.resin,
      leyLine: RESIN_ACTIVITY_COSTS.leyLineOutcrop.resin,
      normalBoss: RESIN_ACTIVITY_COSTS.normalBoss.resin,
      weeklyBossDiscounted: RESIN_ACTIVITY_COSTS.weeklyBoss.firstThreePerWeekResin,
      weeklyBossFull: RESIN_ACTIVITY_COSTS.weeklyBoss.afterFirstThreePerWeekResin,
      condensedResinCraft: 40,
    },
    fragileResinRestores: RESIN_SYSTEM.manualRefill.fragileResinRestores,
    transientResinRestores: RESIN_SYSTEM.manualRefill.transientResinRestores,
  };
}
