import { describe, expect, it } from "vitest";
import { compileChangeSetToOverridePack, createEmptyDatabaseChangeSet } from "../../domain/staticData/databaseChangeSet";
import { createStaticData } from "../../domain/staticData/staticDataFactory";
import { buildKnownKeyLookupIndex, generateKeyFromName, resolveKnownKey } from "./patchManifestResolver";

describe("patchManifestResolver", () => {
  it("resolves exact and normalized known keys without applying them automatically", () => {
    const staticData = createStaticData();
    const index = buildKnownKeyLookupIndex(staticData);
    const key = Object.keys(staticData.localSpecialties)[0];
    const label = staticData.localSpecialties[key].displayName;

    expect(resolveKnownKey(index, "localSpecialty", key)).toMatchObject({
      status: "exact",
      candidates: [expect.objectContaining({ key })],
    });
    expect(resolveKnownKey(index, "localSpecialty", label.toLowerCase())).toMatchObject({
      status: "normalized",
      candidates: [expect.objectContaining({ key })],
    });
  });

  it("includes records generated by the current manifest preview", () => {
    const changeSet = createEmptyDatabaseChangeSet();
    changeSet.localSpecialties.Frostbud = {
      key: "Frostbud",
      displayName: "Frostbud",
      region: "Snezhnaya",
      isPurchasable: false,
      purchaseVendors: [],
      searchHint: "",
      notes: [],
    };

    const previewStaticData = createStaticData(compileChangeSetToOverridePack(changeSet));
    const index = buildKnownKeyLookupIndex(previewStaticData);

    expect(resolveKnownKey(index, "localSpecialty", "frost bud")).toMatchObject({
      status: "normalized",
      candidates: [expect.objectContaining({ key: "Frostbud" })],
    });
  });

  it("suggests candidates for partial input and reports missing keys safely", () => {
    const staticData = createStaticData();
    const index = buildKnownKeyLookupIndex(staticData);

    expect(resolveKnownKey(index, "talentBookFamily", "Prosperi").status).toBe("suggested");
    expect(resolveKnownKey(index, "talentBookFamily", "DefinitelyNotARealFamily")).toMatchObject({
      status: "missing",
      candidates: [],
    });
  });

  it("generates stable PascalCase keys from display names", () => {
    expect(generateKeyFromName("A Day Carved from Rising Winds")).toBe("ADayCarvedFromRisingWinds");
  });
});
